export const membersData = [
	{
		email: 'lisa@example.com',
		username: 'lisa',
		gender: 'female',
		dateOfBirth: '1986-07-22',
		name: 'Lisa',
		created: '2020-06-24',
		lastActive: '2020-06-21',
		description:
			'Sunt esse aliqua ullamco in incididunt consequat commodo. Nisi ad esse elit ipsum commodo fugiat est ad. Incididunt nostrud incididunt nostrud sit excepteur occaecat.\r\n',
		city: 'Greenbush',
		country: 'Martinique',
		image: '/images/f1.jpeg',
		clerkId: 'user_3ABJh0wwzsAi2apIDTagXEQJXgT',
		interests: 'Hiking,Wine,Yoga,Coding',
		lookingFor: 'Long-term relationship',
		height: 168,
		ethnicity: 'Caucasian',
		religion: 'Spiritual',
		education: 'Masters Degree',
		profession: 'UX Designer',
		promptQuestion: 'My ideal first date is...',
		promptAnswer:
			'A sunset walk followed by local tacos and great conversation.',
	},
	{
		email: 'karen@test.com',
		username: 'karen',
		gender: 'female',
		dateOfBirth: '1995-10-12',
		name: 'Karen',
		created: '2019-12-09',
		lastActive: '2020-05-06',
		description:
			'Laborum dolore aliquip voluptate sunt cupidatat fugiat. Aliqua cillum deserunt do sunt ullamco aute Lorem nisi irure velit esse excepteur ex qui. Aliquip cupidatat officia ullamco duis veniam quis elit dolore nisi proident exercitation id cillum ullamco. In exercitation aliqua commodo veniam culpa duis commodo mollit et sint culpa.\r\n',
		city: 'Celeryville',
		country: 'Grenada',
		image: '/images/f2.jpeg',
		clerkId: '1',
		interests: 'Cooking,Tennis,Travel',
		lookingFor: 'Casual dating',
		height: 162,
		ethnicity: 'Hispanic',
		religion: 'None',
		education: 'Bachelors Degree',
		profession: 'Marketing Manager',
		promptQuestion: 'The quickest way to my heart is...',
		promptAnswer: 'Freshly brewed coffee and a playlist of 90s R&B.',
	},
	{
		email: 'margo@test.com',
		username: 'margo',
		gender: 'female',
		dateOfBirth: '1989-01-24',
		name: 'Margo',
		created: '2019-08-10',
		lastActive: '2020-05-12',
		description:
			'Dolor ut mollit sunt fugiat magna do eu et aliqua. Dolor consectetur reprehenderit irure non adipisicing ad irure sint id amet reprehenderit esse consectetur ex. Nisi sunt minim amet dolore eiusmod occaecat commodo nostrud tempor dolore velit. Fugiat labore duis nulla do officia voluptate ullamco. Velit ex ullamco cillum amet qui anim et ullamco adipisicing fugiat exercitation aliqua. Consectetur et do labore enim aliqua occaecat.\r\n',
		city: 'Rosewood',
		country: 'Svalbard and Jan Mayen Islands',
		image: '/images/f3.jpeg',
		clerkId: '2',
		interests: 'Skiing,Reading,Painting',
		lookingFor: 'Marriage',
		height: 170,
		ethnicity: 'Caucasian',
		religion: 'Christian',
		education: 'PhD',
		profession: 'Scientist',
		promptQuestion: 'I’m weirdly competitive about...',
		promptAnswer: 'Mario Kart. I never lose on Rainbow Road.',
	},
	{
		email: 'lois@test.com',
		username: 'lois',
		gender: 'female',
		dateOfBirth: '1988-06-22',
		name: 'Lois',
		created: '2019-04-24',
		lastActive: '2020-06-17',
		description:
			'Cillum elit nostrud enim laboris pariatur laborer ipsum ut. Quis elit irure sint velit laboris anim Lorem laboris. Labore reprehenderit magna officia aliquip pariatur ea id id commodo. Culpa duis non ex nisi. Deserunt pariatur aliqua consequat reprehenderit sunt ex exercitation.\r\n',
		city: 'Orviston',
		country: 'Zimbabwe',
		image: '/images/f4.jpeg',
		clerkId: '4',
		interests: 'Fashion,Gardening,Volunteering',
		lookingFor: 'Life Partner',
		height: 165,
		ethnicity: 'Mixed',
		religion: 'Spiritual',
		education: 'Bachelors Degree',
		profession: 'Nurse',
		promptQuestion: 'My simple pleasure is...',
		promptAnswer: 'The smell of rain on hot pavement and a good book.',
	},
	{
		email: 'ruthie@test.com',
		username: 'ruthie',
		gender: 'female',
		dateOfBirth: '1986-01-12',
		name: 'Ruthie',
		created: '2019-04-30',
		lastActive: '2020-06-21',
		description:
			'Qui ipsum voluptate exercitation officia nisi velit adipisicing exercitation sint nulla do. Qui fugiat non nisi excepteur et duis elit consectetur ullamco velit fugiat. Sit do esse cupidatat quis eiusmod cupidatat.\r\n',
		city: 'Germanton',
		country: 'Antigua and Barbuda',
		image: '/images/f5.jpeg',
		clerkId: '5',
		interests: 'Dancing,Podcasts,Baking',
		lookingFor: 'Serious Relationship',
		height: 160,
		ethnicity: 'Black',
		religion: 'Christian',
		education: 'Associate Degree',
		profession: 'Accountant',
		promptQuestion: 'I’m most productive when...',
		promptAnswer: 'I have a clear to-do list and a lo-fi beats playlist.',
	},
	{
		email: 'todd@test.com',
		username: 'todd',
		gender: 'male',
		dateOfBirth: '1980-02-07',
		name: 'Todd',
		created: '2019-04-29',
		lastActive: '2020-05-16',
		description:
			'Mollit elit cillum dolore ea laboris consequat excepteur eiusmod eiusmod qui magna mollit occaecat. Sint qui ut veniam non. Est non veniam magna in consectetur ullamco eiusmod in elit aute ea ipsum aliquip. Duis nisi do dolore ad. Consectetur incididunt quis exercitation aliquip officia. Ex anim pariatur veniam fugiat aute consequat quis nisi in quis.\r\n',
		city: 'Cliff',
		country: 'British Indian Ocean Territory',
		image: '/images/m1.jpeg',
		clerkId: '6',
		interests: 'Basketball,Gaming,Gym',
		lookingFor: 'Casual Dating',
		height: 185,
		ethnicity: 'African American',
		religion: 'None',
		education: 'Bachelors',
		profession: 'Personal Trainer',
		promptQuestion: 'A life goal of mine is...',
		promptAnswer: 'To run a marathon in under 4 hours.',
	},
	{
		email: 'porter@test.com',
		username: 'porter',
		gender: 'male',
		dateOfBirth: '1997-04-09',
		name: 'Porter',
		created: '2020-04-05',
		lastActive: '2020-06-23',
		description:
			'Qui adipisicing enim mollit magna fugiat. Quis laborum sit adipisicing Lorem veniam magna. Aliqua ex occaecat id duis aute excepteur quis eu eiusmod. Cillum consectetur dolore officia consequat veniam nulla qui occaecat ullamco ipsum sit incididunt aute ullamco.\r\n',
		city: 'Welda',
		country: 'Christmas Island',
		image: '/images/m2.jpeg',
		clerkId: '7',
		interests: 'Surfing,Anime,Photography',
		lookingFor: 'Friendship',
		height: 180,
		ethnicity: 'Caucasian',
		religion: 'Atheist',
		education: 'In College',
		profession: 'Graphic Design Student',
		promptQuestion: 'My favorite way to spend a Sunday...',
		promptAnswer: 'Surfing at dawn then brunch with way too much coffee.',
	},
	{
		email: 'mayo@test.com',
		username: 'mayo',
		gender: 'male',
		dateOfBirth: '1990-03-23',
		name: 'Mayo',
		created: '2020-03-14',
		lastActive: '2020-05-17',
		description:
			'Aliquip labore nisi veniam exercitation sit laborum nisi pariatur dolore tempor irure. Ad officia et eu cupidatat qui irure pariatur qui excepteur dolor ut eiusmod. Exercitation qui cillum elit elit officia elit culpa eu consequat cupidatat velit esse.\r\n',
		city: 'Clarence',
		country: 'Burkina Faso',
		image: '/images/m3.jpeg',
		clerkId: 'user_3ABOZGjkSxuasqlWL9wcroMpuqY',
		interests: 'Photography,Nature,Cooking',
		lookingFor: 'Serious Relationship',
		height: 178,
		ethnicity: 'Asian',
		religion: 'Buddhism',
		education: 'High School',
		profession: 'Chef',
		promptQuestion: 'Two truths and a lie...',
		promptAnswer:
			'I have a twin, I’ve climbed Everest, I speak 4 languages.',
	},
	{
		email: 'skinner@test.com',
		username: 'skinner',
		gender: 'male',
		dateOfBirth: '1982-12-01',
		name: 'Skinner',
		created: '2019-01-28',
		lastActive: '2020-06-07',
		description:
			'Cupidatat dolor irure officia qui consequat ea laborum excepteur esse. Esse qui cupidatat minim laborum velit occaecat officia. Nulla consectetur nisi laborum in eu fugiat ipsum magna. Ipsum sunt consectetur reprehenderit ea consectetur fugiat anim enim nostrud. Ut fugiat cupidatat aliquip ipsum laborum adipisicing sint tempor. Eu deserunt aute Lorem duis exercitation aute aute commodo ut eu elit elit commodo officia.\r\n',
		city: 'Herald',
		country: 'Poland',
		image: '/images/m4.jpeg',
		clerkId: '9',
		interests: 'History,Chess,Jazz',
		lookingFor: 'Marriage',
		height: 175,
		ethnicity: 'Caucasian',
		religion: 'None',
		education: 'Masters Degree',
		profession: 'Historian',
		promptQuestion: 'I’m weirdly obsessed with...',
		promptAnswer: 'Restoring mid-century modern furniture.',
	},
	{
		email: 'davis@test.com',
		username: 'davis',
		gender: 'male',
		dateOfBirth: '1978-03-20',
		name: 'Davis',
		created: '2020-02-25',
		lastActive: '2020-06-11',
		description:
			'Voluptate sunt adipisicing ea nisi ex ullamco veniam dolor. Dolor do et exercitation in. Aute enim pariatur amet commodo. Deserunt consectetur quis culpa aliqua voluptate ipsum exercitation exercitation exercitation ea aliqua sunt.\r\n',
		city: 'Lupton',
		country: 'Luxembourg',
		image: '/images/m5.jpeg',
		clerkId: '10',
		interests: 'Golf,Fishing,Investing',
		lookingFor: 'Long-term',
		height: 182,
		ethnicity: 'Caucasian',
		religion: 'Christian',
		education: 'MBA',
		profession: 'Financial Advisor',
		promptQuestion: 'My greatest strength is...',
		promptAnswer:
			'I can make a killer martini and an even better retirement plan.',
	},
];
